### PR TITLE
Added Test Plan, Scrum for MS02.

### PR DESCRIPTION
**Pull request by SJLEE411**
Added Test Plan, Scrum for MS02. finder.h has been added by Shine Lee(vanthalos). Review approved and Merged by the developer.

### CODE REVIEW

**Review by zxcvbas12 — COMMENTED** [review]
The test contribution did all good

**Review by songhwanOh — COMMENTED** [review]
looks good. I think we can start on implementing them

**Review by ylee237 — APPROVED** [review]
milestone2 final

**Comment by DevVeeLee** [comment]
Great job!

**Pull request merged**
